viniciosarodrigues/gestao-de-prontuario

- src/main/java/br/com/ft/gdp/controller/ResponsibleController.java
- src/main/java/br/com/ft/gdp/exception/HandlerExceptions.java
- src/main/java/br/com/ft/gdp/exception/StandardErrorSpring.java
- src/main/java/br/com/ft/gdp/models/domain/Responsible.java
Criação de tratadores para corpo de requisição com propriedades desconhecidas
> Vini branch

- .circleci/config.yml
Alterando linha de desenvolvimento
> Atualizando o CircleCI

- Procfile
Criando integração com o Heroku
> Criando integração com o Heroku

- .circleci/config.yml
> Atualizando CircleCI

- src/main/java/br/com/ft/gdp/controller/VisitController.java
- src/main/java/br/com/ft/gdp/repository/VisitRepository.java
- src/main/java/br/com/ft/gdp/service/VisitService.java
Criar endpoint que traga uma lista de Visitas baseadas no Identificador do paciente #14
> Criar endpoint que traga uma lista de Visitas baseadas no Identificador do paciente #14

- src/main/java/br/com/ft/gdp/controller/VisitEventController.java
Criar endpoint para a adição de Eventos da Visita #15
> Feature/gestao de prontuario/issues/15

- src/main/java/br/com/ft/gdp/controller/SpecialityController.java
- src/main/java/br/com/ft/gdp/models/domain/Responsible.java
- src/main/java/br/com/ft/gdp/models/domain/Speciality.java
- src/main/java/br/com/ft/gdp/models/dto/ResponsibleDTO.java
- src/main/java/br/com/ft/gdp/models/dto/SpecialityInfoDTO.java
- src/main/java/br/com/ft/gdp/service/SpecialityService.java
Este recurso trás informações sobre a especialidade e os profissionais registrados nela.
> Criação de recurso de pesquisa de Especialidade por ID

- .github/relat-rio-de-erro.md
- .github/relat-rio-de-funcionalidade.md
- PULL_REQUEST_TEMPLATE.md
> Adicionando templates Git

- src/main/java/br/com/ft/gdp/controller/SectorController.java
- src/main/java/br/com/ft/gdp/controller/UserController.java
- src/main/java/br/com/ft/gdp/service/security/AuthService.java
Implementação do Reset de senha.
> Implementação do Reset de senha.

- src/main/java/br/com/ft/gdp/repository/UserRepository.java
- src/main/java/br/com/ft/gdp/service/UserService.java
- src/main/java/br/com/ft/gdp/service/security/AuthService.java
Ativando usuário no momento do cadastro
> Ativando usuário no momento do cadastro

- pom.xml
- src/main/java/br/com/ft/gdp/controller/SectorController.java
- src/main/java/br/com/ft/gdp/exception/GenerateReportException.java
- src/main/java/br/com/ft/gdp/exception/HandlerExceptions.java
- src/main/java/br/com/ft/gdp/report/AttendanceStatement.java
- src/main/java/br/com/ft/gdp/report/ReportFactory.java
- src/main/java/br/com/ft/gdp/report/ReportParam.java
- src/main/java/br/com/ft/gdp/report/ReportType.java
- src/main/resources/reports/dec_comparecimento.jrxml
Criando integração com o Jasper Reports
> Criando integração com o Jasper Reports

- src/main/java/br/com/ft/gdp/report/ReportFactory.java
> Adicionando comentário

- README.md
doc: Atualizando features do readme
> doc: Atualizando features do readme

- src/main/java/br/com/ft/gdp/models/domain/Person.java
- src/main/java/br/com/ft/gdp/models/dto/PatientInfoDTO.java
- src/main/java/br/com/ft/gdp/models/dto/PersonInfoDTO.java
- src/main/java/br/com/ft/gdp/service/PatientService.java
- src/main/java/br/com/ft/gdp/service/PersonService.java
bug: CPF em branco na inserção, dando erro de restrição de chave
> bug: CPF em branco na inserção, dando erro de restrição de chave

- src/main/java/br/com/ft/gdp/models/dto/VisitEventInfoDTO.java
feat: adicionando informações detalhadas da visita/atendimento
> feat: adicionando informações detalhadas da visita/atendimento

- src/main/java/br/com/ft/gdp/service/AttendanceService.java
bug: adicionando tipo de entrada obrigatório
> bug: adicionando tipo de entrada obrigatório

- src/main/java/br/com/ft/gdp/controller/filters/AttendanceFilters.java
- src/main/java/br/com/ft/gdp/repository/custom/attendance/AttendanceRepositoryCustomImpl.java
- src/main/java/br/com/ft/gdp/repository/custom/patient/PatientRepositoryCustomImpl.java
bug: corrigindo filtro por tipo de paciente
> bug: corrigindo filtro por tipo de paciente

- src/main/java/br/com/ft/gdp/models/dto/AttendanceDTO.java
- src/main/java/br/com/ft/gdp/models/dto/DataTransferObjectBase.java
- src/main/java/br/com/ft/gdp/repository/custom/attendance/AttendanceRepositoryCustomImpl.java
feat: adicionando tipo de paciente ao Atendimento
> feat: adicionando tipo de paciente ao Atendimento

- src/main/java/br/com/ft/gdp/service/SectorService.java
bug: corrigindo setor com identificador nulo na abertura de atendimento
> bug: corrigindo setor com identificador nulo na abertura de atendimento

- src/main/java/br/com/ft/gdp/service/InstituteService.java
feat: adicionando informações do cliente nas informações institucionais
> feat: adicionando informações do cliente nas informações institucionais

- src/main/java/br/com/ft/gdp/service/InstituteService.java
bug: adiciona informações de endereço e licença
> bug: adiciona informações de endereço e licença

- src/main/java/br/com/ft/gdp/models/domain/Institute.java
- src/main/resources/application-dev.properties
- src/main/resources/application-heroku.properties
- src/main/resources/application.properties
- src/main/resources/db/migration/V000060__ALTERANDO_ESTRUTURA_DE_PARAMETROS_ERRADOS.sql
bug: correção de parâmetros e informações do instituto
> bug: correção de parâmetros e informações do instituto

- src/main/java/br/com/tl/gdp/models/dto/ParameterDTO.java
feat: adicionando propriedade de parâmetro de grupo
> feat: adicionando propriedade de parâmetro de grupo

- src/main/java/br/com/tl/gdp/service/InstituteService.java
bug: correção de parâmetro inválido
> bug: correção de parâmetro inválido

- src/main/java/br/com/tl/gdp/service/InstituteService.java
bug: corrigindo null pointer em parâmetro nulo
> bug: corrigindo null pointer em parâmetro nulo

- src/main/java/br/com/tl/gdp/controller/ParameterController.java
- src/main/java/br/com/tl/gdp/repository/custom/patient/PatientRepositoryCustomImpl.java
- src/main/java/br/com/tl/gdp/repository/custom/responsible/ResponsibleRepositoryCustomImpl.java
- src/main/java/br/com/tl/gdp/service/InstituteService.java
- src/main/java/br/com/tl/gdp/service/ParameterService.java
- src/main/java/br/com/tl/gdp/util/StringUtils.java
- src/main/resources/db/migration/V000062__CRIANDO_NOVOS_PAPEIS_PARA_PARAMETROS.sql
feat: adicionando endpoint para alteração de valor de parâmetro
> feat: adicionando endpoint para alteração de valor de parâmetro

- src/main/java/br/com/tl/gdp/models/enums/MetaType.java
- src/main/java/br/com/tl/gdp/service/ParameterService.java
bug: correção para parâmetros do tipo texto e senha
> bug: correção para parâmetros do tipo texto e senha

- src/main/java/br/com/nivlabs/gp/config/SwaggerConfig.java
- src/main/java/br/com/nivlabs/gp/controller/ParameterController.java
- src/main/java/br/com/nivlabs/gp/models/dto/NewParameterValueDTO.java
- src/main/java/br/com/nivlabs/gp/service/ParameterService.java
bug: corrigindo alteração de parâmetros nulos
> bug: corrigindo alteração de parâmetros nulos

- pom.xml
down: realizando downgrade não versão do Spring devido ao MySql
> down: realizando downgrade não versão do Spring devido ao MySql

- pom.xml
- system.properties
down: realizando downgrade no Java
> down: realizando downgrade no Java

- pom.xml
- system.properties
updt: retornando update inicial pós upgrade do banco
> updt: retornando update inicial pós upgrade do banco

- src/main/java/br/com/nivlabs/gp/repository/custom/procedureorevent/ProcedureOrEventRepositoryCustomImpl.java
bug: correção de propriedade no filtro dinâmico
> bug: correção de propriedade no filtro dinâmico

- src/main/java/br/com/nivlabs/gp/controller/filters/ProcedureOrEventFilters.java
- src/main/java/br/com/nivlabs/gp/repository/custom/procedureorevent/ProcedureOrEventRepositoryCustomImpl.java
bug: ajuste em filtros de Procedimentos
> bug: ajuste em filtros de Procedimentos
